name: Publish to GitHub Packages

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # TODO: ã“ã®ã‚­ãƒ£ãƒƒã‚·ãƒ¥å‡¦ç†ãŒmainã«ä¾å­˜ã—ã¦ã„ã‚‹ã®ã§ã©ã†ã«ã‹åˆ†é›¢ã—ãŸã„
      - uses: actions/cache/restore@v3
        with:
          path: ./dist/
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-
          fail-on-cache-miss: true

      - name: Configure .npmrc for GitHub Packages
        run: |
          cat << EOF > .npmrc
          @koumatsumoto:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm version --no-commit-hooks --no-git-tag-version --allow-same-version ${{inputs.version}}
      - run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package name and version
        id: package_info
        run: |
          echo "package_name=`node -p 'require(\"./package.json\").name'`" >> "$GITHUB_ENV"
          echo "package_version=`node -p 'require(\"./package.json\").version'`" >> "$GITHUB_ENV"

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const heading = 'New GitHub Packages'
            const output = `
              *New Version* ğŸ¤– \`${{ inputs.version }}\`\n
              \`npm install ${{ env.package_name }}/${{ env.package_version }}\`\n
            `;
            await core.summary
              .addHeading(heading)
              .addRaw(output)
              .write()
